### PR TITLE
Allow frame filter to be specified via GCC2SS_INCLUDE env var

### PR DESCRIPTION
**Pull request by bamboo**
For example, to more quickly get an overview of which tasks are using more space, the following command line would work:

    GCC2SS_INCLUDE=":.+" gcc2ss debug.log >> tasks.json

### CODE REVIEW

**Comment by abstratt** [comment]
@bamboo I missed one line/paragraph/sample in the README showing how to use this variable. It is true there isn't one for "GCC2SS_CHANNEL_CAPACITY" either but still...

**Review by abstratt — APPROVED** [review]
Looks good, one doc'ing suggestion

**Comment by bamboo** [comment]
> I missed one line/paragraph/sample in the README showing how to use this variable.

Thanks, will add one.

**Comment by bamboo** [comment]
> @bamboo I missed one line/paragraph/sample in the README showing how to use this variable.

This has been done.

**Pull request merged**
